### ISSUE TITLE
页面布局修改

### ISSUE THREAD

**Issue by wangdayong228** [conflux-fans/conflux-faucet#2]
页面布局修改：
1. 用1行展示主要信息，顺序为 “请选择要领取的代币     代币选择下拉框      领取按钮”；

领取按钮根据当前状态显示不同文案，参考moonswap
1. 未安装protal时显示 "请安装conflux portal"，点击后打开portal官网
2. 未连接portal时显示"请连接钱包"
3. 未选择代币时显示“请选择代币”

其余按图中提示修改
1. 代币余额不显示
2. 代币池余额不显示
3. 下方增加一些领取规则说明，包括 每次领取的代币数量及领取间隔时长、领取步骤等， 参考 https://faucet.ropsten.be/
![image](https://user-images.githubusercontent.com/11971608/119488687-69eb5180-bd8d-11eb-8d1a-499133c0eb56.png)

**Comment by darwintree** [comment]
除说明部分尚未完成外，其余需要隐藏的部分已默认隐藏

**Comment by darwintree** [comment]
done

**Comment by wangdayong228** [comment]
good job
