### ISSUE TITLE
取消授权后页面“连接钱包”按钮状态没有刷新

### ISSUE THREAD

**Issue by wangdayong228** [conflux-fans/conflux-faucet#3]
如图，取消授权后，按钮还是连接状态
![image](https://user-images.githubusercontent.com/11971608/119596209-541f7000-be11-11eb-9d5d-f16611882fee.png)

**Comment by darwintree** [comment]
我这里无法复现。是否有更详细的复现步骤？

**Comment by wangdayong228** [comment]
刚才测没有这个问题了，再碰到了再看吧
